name: Build Windows EXE (Stable Python 3.9)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # CAMBIO CLAVE: Usamos Python 3.9
      # Esta versión evita el error de recursión de ntpath que da la 3.10
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos las librerías necesarias
          pip install kivy==2.2.1 kivymd==1.2.0 pillow reportlab pyinstaller
          # Dependencias gráficas para Windows
          pip install kivy_deps.angle kivy_deps.glew kivy_deps.sdl2

      - name: Build EXE with PyInstaller
        # KIVY_GL_BACKEND: angle_sdl2 -> Evita el crash por falta de gráfica en GitHub
        # --hidden-import win32timezone -> Asegura que funcionen las fechas
        env:
          KIVY_GL_BACKEND: angle_sdl2
        run: |
          pyinstaller --name GlassDoorPC --onefile --noconsole --collect-all kivymd --hidden-import win32timezone main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: GlassDoorPC-Ejecutable
          path: dist/GlassDoorPC.exe
